name: Docker Build, Tag, and Release

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper tag calculation

      - name: Ensure full git history
        run: git fetch --prune --unshallow || echo "Already unshallowed"

      - name: Calculate version and create tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        with:
          default_bump: "patch"     # You can set this to minor or major as desired
          tag_prefix: "v"           # Adjust prefix if needed
          release_branches: "main"  # Only bump on main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mydockerhubuser/myimage:${{ steps.tag_version.outputs.new_tag }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push mydockerhubuser/myimage:${{ steps.tag_version.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
