name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest coverage bandit safety mypy

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Type Check with mypy
        run: |
          mypy .

      - name: Run Unit Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run Coverage Report
        run: |
          coverage run -m pytest
          coverage report

      - name: Run Bandit for Security Analysis
        run: |
          bandit -r .

      - name: Check for Dependency Vulnerabilities
        run: |
          safety check --full-report

  # Optional Docker build job
  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest .
